controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /
    methods: [GET]
    controller: App\Controller\DefaultController::index

login:
    path: /login
    methods: [GET, POST]
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    methods: [GET]
    controller: App\Controller\SecurityController::logout

task_list:
    path: /tasks
    methods: [GET]
    controller: App\Controller\TaskController::index

task_create:
    path: /tasks/create
    methods: [GET, POST]
    controller: App\Controller\TaskController::create

task_edit:
    path: /tasks/{id}/edit
    methods: [GET, POST]
    controller: App\Controller\TaskController::edit

task_toggle:
    path: /tasks/{id}/toggle
    methods: [GET]
    controller: App\Controller\TaskController::toggle

task_delete:
    path: /tasks/{id}/delete
    methods: [GET]
    controller: App\Controller\TaskController::delete

user_list:
    path: /users
    methods: [GET]
    controller: App\Controller\UserController::indexList

user_create:
    path: /users/create
    methods: [GET, POST]
    controller: App\Controller\UserController::create

user_edit:
    path: /users/{id}/edit
    methods: [GET, POST]
    controller: App\Controller\UserController::edit
